### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tubcx** [RMJTromp/ChatEmojis#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Why will appear after garbled input instructions
**Screenshots**
![2%H8WQCK0{ Z_93HYE `ES9](https://user-images.githubusercontent.com/112924956/188555457-4f4dd463-4cd1-466c-9d6f-a10097c30372.png)

**Server Jar & Version (please complete the following information):**
 - Jar: [e.g. Spigot1.8.8]
 - Version: [e.g. 1.8.9]

**Additional context**

**Comment by RMJTromp** [comment]
I have no clue what you're trying to report.
You haven't provided a description, what you expected to happen and what really happened, and how you produced this bug.
I don't know what I am supposed to do with this (lack of) information.

Though, I am going to make a wild guess that this is happening because your Minecraft is set to a different language?
